# Configuração do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestaoveiculos
spring.datasource.username=root
spring.datasource.password=

# Configuração do Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do JPA (Hibernate)
# ddl-auto: update é para criar/atualizar a tabela Marca no seu banco automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081